
IMAGE_HEIGHT = 299
IMAGE_WIDTH = 299
IMAGE_CHANNEL = 3

MAX_TOP_K = 10
CLASSES = 1000

BATCH_SIZE = 32
WEIGHT_DECAY = 5e-5

# LSEP
INIT_LEARNING_RATE = 1e-2
LOG_ITERATION = 50
VALID_ITERATION = 10000

# REPLACE_JSON_DIR = 'C:/public/NUS_WIDE/json/'
# LABEL_TXT_PATH = 'C:/public/NUS_WIDE/NUS_WID_Tags/TagList1k.txt'

REPLACE_JSON_DIR = 'D:/DB/NUS_WIDE/json/'
LABEL_TXT_PATH = 'D:/DB/NUS_WIDE/NUS_WID_Tags/TagList1k.txt'
